
# Configuration de build Netlify pour FileChat
[build]
  publish = "dist"
  command = "npm run build"

# Configuration des variables d'environnement par défaut
[build.environment]
  NODE_VERSION = "18"

# Configuration des redirections pour le routage SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirection API pour les fonctions Edge
[[redirects]]
  from = "/api/oauth/*"
  to = "https://dbdueopvtlanxgumenpu.supabase.co/functions/v1/unified-oauth"
  status = 200
  force = true

[[redirects]]
  from = "/api/drive/*"
  to = "https://dbdueopvtlanxgumenpu.supabase.co/functions/v1/index-google-drive"
  status = 200
  force = true

[[redirects]]
  from = "/api/batch-drive/*"
  to = "https://dbdueopvtlanxgumenpu.supabase.co/functions/v1/batch-index-google-drive"
  status = 200
  force = true

[[redirects]]
  from = "/api/secure-proxy/*"
  to = "https://dbdueopvtlanxgumenpu.supabase.co/functions/v1/secure-api-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/rag/*"
  to = "https://dbdueopvtlanxgumenpu.supabase.co/functions/v1/advanced-rag-generation"
  status = 200
  force = true

# En-têtes pour améliorer la sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co http://localhost:* ws://localhost:* https://* wss://*; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://*;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
