
# Configuration for Netlify Build for FileChat
[build]
  publish = "dist"
  command = "node scripts/netlify-prebuild.js && npm run build"

# Default environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefer-offline --no-audit --no-fund"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NO_RUST_INSTALL = "1"
  NETLIFY_USE_YARN = "false"
  TRANSFORMERS_OFFLINE = "1"
  CI = "true"
  SKIP_PYTHON_INSTALLATION = "true"
  NETLIFY_SKIP_PYTHON_REQUIREMENTS = "true"
  VITE_CLOUD_MODE = "true"
  VITE_ALLOW_LOCAL_AI = "false"

# SPA routing redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  
# Redirect APIs to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["**/*.model"]
  external_node_modules = ["@supabase/supabase-js"]

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co http://localhost:* ws://localhost:* https://* wss://* /.netlify/functions/*; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.gpteng.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://*; worker-src 'self' blob:;"

# Specific MIME type headers for JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
