apiVersion: v1
kind: ServiceAccount
metadata:
  name: supabase-compat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: supabase-compat
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: supabase-compat
roleRef:
  kind: Role
  name: supabase-compat
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: supabase-compat
  namespace: default 